#!/usr/bin/env python

import requests
from dateutil.parser import parse
import pytz
import pdb


def getSunriseDatetime(lat, lng):
	# Sunrise Sunset provides our sunrise and sunset times: http://sunrise-sunset.org/api
	# Datetime is UTC

	sunJson = requests.get("http://api.sunrise-sunset.org/json?lat={}&lng={}&date=tomorrow&formatted=0".format(lat, lng)).json()
	sunriseTimeString = sunJson['results']['sunrise']

	# Sample sunriseTimeString: 2016-04-21T13:24:28+00:00
	return parse(sunriseTimeString)

def main():
	hueToken = "DfVZeleoILd4pIe2ZvM2UfVCcea9OiBbH8biB49b"
	alarmId = "0415713780126651"
	hueUrl = "http://192.168.1.137/api/{}/schedules/{}".format(hueToken, alarmId)

	weekBitmask = 124

	# Lat & Long for San Francisco, CA, USA are 37.7749, -122.4194
	sunriseUtc = getSunriseDatetime(37.7749, -122.4194)

	pacific = pytz.timezone('US/Pacific')
	sunriseDt = sunriseUtc.astimezone(pacific)
	hueTime = "W{}/T{}".format(weekBitmask, sunriseDt.strftime("%H:%M:%S"))
	
	payload = {"localtime":hueTime}
	result = requests.put(hueUrl, json=payload)
	print result.json()

if __name__ == "__main__":
    main()